<?php

/**
 * @file
 * Primary module hooks for Exchange rates module.
 */

/**
 * Implements hook_theme().
 */
function exchange_rates_theme($existing, $type, $theme, $path) {
  return [
    'block_exchange_rates' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
  ];
}

///**
// * Implements hook_page_attachments().
// */
//function exchange_rates_page_attachments(array &$attachments) {
//  $attachments['#attached']['library'][] = 'exchange_rates/exchange_rates_chart';
//}
