<?php


/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */

function newsweek_theme_suggestions_block_alter(&$suggestions, $variables) {
  if (isset($variables['elements']['content']['#block_content'])) {
    $bundle = $variables['elements']['content']['#block_content']->bundle();
    $view_mode = $variables['elements']['content']['#view_mode'];
    $suggestions[] = 'block__' . $bundle . '__' . "$view_mode";
  }
}
