<?php

/**
 * @file
 * Primary module hooks for Article Title Override module.
 */

use Drupal\Component\Utility\NestedArray;

/**
 * Implements hook_preprocess_HOOK().
 */
function article_title_override_preprocess_page(&$variables) {
  $parents = ['page', 'content', 'bartik_page_title', '#block'];
  $block_title = NestedArray::keyExists($variables, $parents);

  if ($block_title) {
    $variables['page']['content']['bartik_page_title']['#block'] = NULL;

  }

}
